/**
 * Экспортёр для .strings формата (iOS/macOS)
 */

/**
 * Экспортирует объект в iOS .strings формат
 */
export function exportToStrings(data: Record<string, any>, locale?: string): string {
  let output = '';
  
  if (locale) {
    output += `// ${locale}.strings\n`;
  }
  output += '// Generated by i18n-ai\n\n';

  const entries = flattenObject(data);
  
  for (const [key, value] of Object.entries(entries)) {
    if (typeof value === 'string') {
      const escapedValue = escapeStringValue(value);
      const escapedKey = escapeStringValue(key);
      output += `"${escapedKey}" = "${escapedValue}";\n`;
    }
  }

  return output;
}

/**
 * Импортирует .strings файл в объект
 */
export function importFromStrings(content: string): Record<string, any> {
  const result: Record<string, any> = {};

  // Удаляем комментарии
  const lines = content.split('\n').filter(line => {
    const trimmed = line.trim();
    return trimmed && !trimmed.startsWith('//') && !trimmed.startsWith('/*');
  });

  // Парсим "key" = "value";
  const lineRegex = /"([^"\\]*(?:\\.[^"\\]*)*)"\s*=\s*"([^"\\]*(?:\\.[^"\\]*)*)"\s*;/;
  
  for (const line of lines) {
    const match = lineRegex.exec(line);
    if (match) {
      const key = unescapeStringValue(match[1]);
      const value = unescapeStringValue(match[2]);
      result[key] = value;
    }
  }

  return result;
}

/**
 * Экранирует специальные символы в строке
 */
function escapeStringValue(value: string): string {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
}

/**
 * Декодирует экранированные символы
 */
function unescapeStringValue(value: string): string {
  return value
    .replace(/\\"/g, '"')
    .replace(/\\\\/g, '\\')
    .replace(/\\n/g, '\n')
    .replace(/\\r/g, '\r')
    .replace(/\\t/g, '\t');
}

/**
 * Преобразует вложенный объект в плоский для .strings формата
 */
function flattenObject(obj: Record<string, any>, prefix: string = ''): Record<string, any> {
  const result: Record<string, any> = {};

  for (const [key, value] of Object.entries(obj)) {
    const newKey = prefix ? `${prefix}.${key}` : key;
    
    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      Object.assign(result, flattenObject(value, newKey));
    } else {
      result[newKey] = value;
    }
  }

  return result;
}

export default {
  exportToStrings,
  importFromStrings
};
